--Q1.	What is the total revenue generated by male vs. female customers?
SELECT 
    gender, 
    SUM(purchase_amount) as revenue
FROM dbo.customer
GROUP BY gender

--Q2.	Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, 
	purchase_amount
FROM dbo.customer
WHERE discount_applied = 'Yes' 
  AND purchase_amount >=
      (SELECT AVG(purchase_amount) 
	   FROM dbo.customer)

--Q3.	Which are the top 5 products with the highest average review rating?
SELECT TOP 5
       item_purchased,
       COUNT(review_rating) AS review_count,
       ROUND(AVG(review_rating),2) AS avg_review_rating
FROM dbo.customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC

--Q4.	What is the average purchase amount between Standard and Express Shipping?
SELECT
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amount
FROM dbo.customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5.	Do subscribed customers spend more? 
--Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(*) AS customers_count,
    AVG(purchase_amount) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM dbo.customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_purchase_amount DESC

--Q6.	Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    COUNT(*) AS total_purchases,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS discounted_purchases,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM dbo.customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;


--Q7. 	Segment customers based on frequency and loyal based on their total number 
-- of previous purchases, and show the count of each category. 
SELECT
    customer_segment,
    COUNT(*) AS customers_count
FROM (
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases <= 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.customer
) s
GROUP BY customer_segment
ORDER BY customers_count DESC

--Q8. 	What are the top 3 most purchased products within each category?
WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM dbo.customer
    GROUP BY category, item_purchased
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM product_counts
WHERE rn <= 3
ORDER BY category, purchase_count DESC;

--Q9.	Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS repeat_buyers_count
FROM dbo.customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10	What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM dbo.customer
GROUP BY age_group
ORDER BY total_revenue DESC;

